# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# GitHub Actions workflow for deploying a Next.js site to GitHub Pages
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      
      - name: Install Backend Dependencies
        working-directory: firstcare-backend
        run: npm ci
      
      - name: Install Frontend Dependencies
        working-directory: firstcare-frontend
        run: npm ci
      
      - name: Build Next.js App
        working-directory: firstcare-frontend
        run: npm run build
      
      - name: Export Static Files
        working-directory: firstcare-frontend
        run: npm run export

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: firstcare-frontend/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
